[package]
name = "octant-object"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = { workspace = true }
octant-reffed=  {workspace=true}
octant-object-derive = {workspace=true}
marshal-pointer = {workspace=true}
