[workspace]
resolver = "2"

members = ["octant-build",
    "octant-client", "octant-gui", "octant-gui-client", "octant-gui-core", "octant-object", "octant-panic", "octant-scoreboard",
    "octant-server"
    , "wasm-error", "octant-build", "octant-database", "octant-account"]

[profile.release]
opt-level = "s"

[patch.crates-io]
base64urlsafedata = {git = "https://github.com/nathdobson/webauthn-rs.git"}
webauthn-rs = {git=  "https://github.com/nathdobson/webauthn-rs.git"}
webauthn-rs-core = {git=  "https://github.com/nathdobson/webauthn-rs.git"}
webauthn-rs-proto = {git=  "https://github.com/nathdobson/webauthn-rs.git"}