[package]
name = "wasm-error"
version = "0.1.0"
edition = "2021"

[dependencies]
sendable = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true, features = ["console"] }
log = { workspace = true }
anyhow = { workspace = true, features= ["backtrace"] }
