[package]
name = "wasm-error"
version = "0.1.0"
edition = "2021"

[dependencies]
sendable = "0.6.1"
wasm-bindgen = "0.2.87"
web-sys = { version = "0.3.64", features = [] }
log= "0.4.20"
anyhow = "1.0.75"