[package]
name = "octant-server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
warp = "0.3.5"
futures = "0.3.28"
anyhow = "1.0.75"
log = "0.4.20"