[package]
name = "octant-object-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = {workspace=true}
syn = {workspace=true, features=["extra-traits","full"]}
quote = {workspace=true}
convert_case = {workspace=true}