[package]
name = "octant-serde"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { workspace = true }
catalog = { workspace = true }
serde = { workspace = true, features = ["derive"] }
type-map = { workspace = true }
anyhow = {workspace=true}
