[package]
name = "octant-scoreboard"
version = "0.1.0"
edition = "2021"

[dependencies]
octant-server = { path = "../octant-server" }
simple_logger = "4.3.3"
tokio = { version = "1.32.0", features = ["rt", "rt-multi-thread", "macros"] }