[package]
name = "octant-database"
version = "0.1.0"
edition = "2021"

[dependencies]
serde={version="1.0.197",features = ["derive"]}
serde_assert = "0.7.1"
tokio={version="1.36.0",features = ["io-util","rt","macros"]}
serde_json = "1.0.114"
anyhow = "1.0.80"
tmpdir = "1.0.0"