[package]
name = "octant-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
atomic_refcell = "0.1.11"
futures = "0.3.28"
anyhow = "1.0.75"
octant-gui-core = { path = "../octant-gui-core" }
serde_json = "1.0.105"